[package]
name = "todo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.13"
ic-cdk-macros = "0.15.0"
ic-cdk-timers = "0.7"
serde = "1.0.204"
